- examples/mock/mockoon-bbidentity.json
- test/features/client_update.feature
- test/features/support/client_update.js
- test/features/support/helpers/helpers.js
Create test configuration for /client-mgmt/oidc-client/{client_id} endpoint from https://github.com/GovStackWorkingGroup/bb-identity/pull/6. This should include all the steps that are pointed out in the parent ticket acceptance criteria.
TICKET: https://govstack-global.atlassian.net/browse/TECH-133
> TECH-133: Create test configuration for "/client-mgmt/oidc-client/{client_id}" endpoint

- examples/mock/mockoon-bbidentity.json
- test/features/client_create.feature
- test/features/support/client_create.js
- test/features/support/helpers/helpers.js
Create test configuration for "/client-mgmt/oidc-client" endpoint 
Create test configuration for /client-mgmt/oidc-client endpoint from https://github.com/GovStackWorkingGroup/bb-identity/pull/6. This should include all the steps that are pointed out in the parent ticket acceptance criteria.
TICKET: https://govstack-global.atlassian.net/browse/TECH-132
> TECH-132: Create test configuration for "/client-mgmt/oidc-client" endpoint 

- examples/mock-identity/mockoon-bbidentity.json
- test/openAPI/features/client_create.feature
- test/openAPI/features/support/client_create.js
- test/openAPI/features/support/helpers/helpers.js
- test/openAPI/package.json
Create cucumber test for POST /client-mgmt/oidc-client
Ticket: https://govstack-global.atlassian.net/browse/TECH-481
> TECH-481: Create cucumber test for bb-identity POST /client-mgmt/oidc-client

- examples/mock-identity/mockoon-bbidentity.json
- test/openAPI/features/client_update.feature
- test/openAPI/features/support/client_update.js
- test/openAPI/features/support/helpers/helpers.js
Update bb-identity PUT /client-mgmt/oidc-client/{client_id}
Ticket: https://govstack-global.atlassian.net/browse/TECH-482
> TECH-482: Update bb-identity PUT /client-mgmt/oidc-client/{client_id}

- examples/mock-identity/mockoon-bbidentity.json
- test/openAPI/features/oidc_authorize.feature
- test/openAPI/features/support/helpers/helpers.js
- test/openAPI/features/support/oidc_authorize.js
Update bb-identity GET /authorize
Ticket: https://govstack-global.atlassian.net/browse/TECH-483
> TECH-483: Update bb-identity GET /authorize

- examples/mock-identity/mockoon-bbidentity.json
- test/openAPI/features/support/helpers/helpers.js
- test/openAPI/features/support/wallet_generate_link_code.js
- test/openAPI/features/wallet_generate_link_code.feature
Create cucumber test for POST /linked-authorization/link-code
Ticket: https://govstack-global.atlassian.net/browse/TECH-646
> TECH-646: Create cucumber test for POST /linked-authorization/link-code

- examples/mock-identity/mockoon-bbidentity.json
- test/openAPI/features/support/helpers/helpers.js
- test/openAPI/features/support/wallet_generate_link_code.js
- test/openAPI/features/support/wallet_list_status.js
- test/openAPI/features/wallet_generate_link_code.feature
- test/openAPI/features/wallet_link_status.feature
Create cucumber test for POST /linked-authorization/link-status
Ticket: https://govstack-global.atlassian.net/browse/TECH-647
> TECH-647: Create cucumber test for POST /linked-authorization/link-status

- examples/mock-identity/mockoon-bbidentity.json
- test/openAPI/features/support/helpers/helpers.js
- test/openAPI/features/support/wallet_link_transaction.js
- test/openAPI/features/support/wallet_list_status.js
- test/openAPI/features/wallet_link_transaction.feature
Create cucumber test for POST /linked-authorization/link-transaction
Ticket: https://govstack-global.atlassian.net/browse/TECH-649
> TECH-649: Create cucumber test for POST /linked-authorization/link-transaction

- examples/mock-identity/mockoon-bbidentity.json
- test/openAPI/features/support/helpers/helpers.js
- test/openAPI/features/support/wallet_generate_link_auth_code.js
- test/openAPI/features/support/wallet_generate_link_code.js
- test/openAPI/features/wallet_generate_link_auth_code.feature
Ticket: https://govstack-global.atlassian.net/browse/TECH-648
> TECH-648: cucumber tests for POST /linked-authorization/link-auth-code

- examples/mock-identity/mockoon-bbidentity.json
- test/openAPI/features/support/helpers/helpers.js
- test/openAPI/features/support/wallet_generate_link_code.js
- test/openAPI/features/support/wallet_linked_authenticate.js
- test/openAPI/features/wallet_linked_authenticate.feature
Create cucumber test for POST /linked-authorization/authenticate
Ticket: https://govstack-global.atlassian.net/browse/TECH-650
> TECH-650: Create cucumber test for POST /linked-authorization/authenticate

- examples/mock-identity/mockoon-bbidentity.json
- test/openAPI/features/support/helpers/helpers.js
- test/openAPI/features/support/wallet_binding.js
- test/openAPI/features/wallet_binding.feature
Ticket: https://govstack-global.atlassian.net/browse/TECH-652
> TECH-652: Cucumber test for POST /wallet-binding

- api/Identity-Provider.yaml
Also an error code of invalid request is added all necessary endpoint to take care of cases like invalid request time
> GOV-602 :  Updated redirect URIs to be required field for create OIDC client endpoint

- test/openAPI/test-data.json
Create a file with the data used in Identity BB 
Ticket: https://govstack-global.atlassian.net/browse/TECH-690
> TECH-690: Create a file with the data used in Identity BB 

- examples/mock-identity/mockoon-bbidentity.json
- test/openAPI/features/support/helpers/helpers.js
- test/openAPI/features/support/wallet_linked_authenticate.js
- test/openAPI/features/wallet_linked_authenticate.feature
Add fixes to BB-Identity POST /linked-authorization/authenticate
Ticket: https://govstack-global.atlassian.net/browse/TECH-734
- https://github.com/GovStackWorkingGroup/bb-identity/pull/35#discussion_r1218166177
- https://github.com/GovStackWorkingGroup/bb-identity/pull/35#discussion_r1218183454
- https://github.com/GovStackWorkingGroup/bb-identity/pull/35#discussion_r1218184325
- https://github.com/GovStackWorkingGroup/bb-identity/pull/35#discussion_r1218185056
> TECH-734: Add fixes to POST /linked-authorization/authenticate

- test/openAPI/features/support/wallet_consent.js
Add fixes to BB-Identity POST /linked-authorization/consent
Ticket: https://govstack-global.atlassian.net/browse/TECH-733
- https://github.com/GovStackWorkingGroup/bb-identity/pull/38#discussion_r1218254077
> TECH-733: Add fixes to BB-Identity POST /linked-authorization/consent

- examples/mock-identity/mockoon-bbidentity.json
- test/openAPI/features/support/helpers/helpers.js
- test/openAPI/features/support/wallet_link_transaction.js
- test/openAPI/features/wallet_link_transaction.feature
Add fixes to BB-Identity POST /linked-authorization/link-transaction
Ticket: https://govstack-global.atlassian.net/browse/TECH-723
- https://github.com/GovStackWorkingGroup/bb-identity/pull/33#discussion_r1210642145
- https://github.com/GovStackWorkingGroup/bb-identity/pull/33#discussion_r1210649210
> TECH-723: Add fixes to BB-Identity POST /linked-authorization/link-transaction

- examples/mock-identity/mockoon-bbidentity.json
- test/openAPI/features/support/helpers/helpers.js
- test/openAPI/features/support/wallet_generate_link_code.js
- test/openAPI/features/support/wallet_linked_authenticate.js
- test/openAPI/features/wallet_generate_link_code.feature
- test/openAPI/features/wallet_linked_authenticate.feature
Add fixes to BB-Identity POST /linked-authorization/link-code
Ticket: https://govstack-global.atlassian.net/browse/TECH-725
- https://github.com/GovStackWorkingGroup/bb-identity/pull/31#discussion_r1209730463
- https://github.com/GovStackWorkingGroup/bb-identity/pull/31#discussion_r1209731708
- https://github.com/GovStackWorkingGroup/bb-identity/pull/31#discussion_r1209732117
- https://github.com/GovStackWorkingGroup/bb-identity/pull/31#discussion_r1209732707
> TECH-725: Add fixes to BB-Identity POST /linked-authorization/link-code

- examples/mock-identity/mockoon-bbidentity.json
- test/openAPI/features/support/helpers/helpers.js
- test/openAPI/features/support/wallet_link_status.js
- test/openAPI/features/wallet_link_status.feature
- test/openAPI/test-data.json
Add fixes to BB-Identity POST /linked-authorization/link-status
Ticket: https://govstack-global.atlassian.net/browse/TECH-724
- https://github.com/GovStackWorkingGroup/bb-identity/pull/32#discussion_r1210069340
- https://github.com/GovStackWorkingGroup/bb-identity/pull/32#discussion_r1210615407
- https://github.com/GovStackWorkingGroup/bb-identity/pull/32#discussion_r1210620153
- https://github.com/GovStackWorkingGroup/bb-identity/pull/32#discussion_r1210628681
> TECH-724: Add fixes to BB-Identity POST /linked-authorization/link-status

- examples/mock-identity/mockoon-bbidentity.json
- test/openAPI/features/support/helpers/helpers.js
- test/openAPI/features/support/wallet_generate_link_auth_code.js
- test/openAPI/features/wallet_generate_link_auth_code.feature
- test/openAPI/test-data.json
Ticket: https://govstack-global.atlassian.net/browse/TECH-731
updated based on comments from: https://github.com/GovStackWorkingGroup/bb-identity/pull/34
> TECH-731: Add fixes to POST /linked-authorization/link-auth-code

- Dockerfile
One of the comments incluced an incorrect filename.
> ID-245 fix minor spelling mistake in Dockerfile
